export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REDUCE_ITEM = "CART_REDUCE_ITEM";
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_EMPTY = "CART_EMPTY";