const data = {
    products: [
        {
            name: 'Smart house',
            category: 'House',
            image: '/images/p1.jpg',
            price: 1050000,
            countInStock: 10,
            brand: 'House',
            rating: 4.5,
            numReviews: 10,
            description: 'Affordable house',
        },
        {
            name: 'Skirt calim',
            category: 'Dress',
            image: '/images/dress1.jpg',
            price: 150000,
            countInStock: 9,
            brand: 'Gucci',
            rating: 4.0,
            numReviews: 1,
            description: 'Affordable dress',
        },
        {
            name: 'New spring dress',
            category: 'Dress',
            image: '/images/dress2.jpg',
            price: 245000,
            countInStock: 5,
            brand: 'Prada',
            rating: 3.8,
            numReviews: 15,
            description: 'Comfortable dress that can be realy good on vacation',
        },
        {
            name: 'old school Rolex',
            category: 'Watch',
            image: '/images/watch1.jpg',
            price: 20000,
            countInStock: 5,
            brand: 'Rolex',
            rating: 3.8,
            numReviews: 15,
            description: 'Good quality watch',
        },
        {
            name: ' Casual watch',
            category: 'Watch',
            image: '/images/watch2.jpg',
            price: 216000,
            countInStock: 5,
            brand: 'Rolex',
            rating: 4.0,
            numReviews: 15,
            description: 'Good quality watch',
        },
        {
            name: 'Dancing dress',
            category: 'Dress',
            image: '/images/dress3.jpg',
            price: 251000,
            countInStock: 9,
            brand: 'Prada',
            rating: 3.0,
            numReviews: 15,
            description: 'Realy stylish dress that is comfortable while dancing',
        },
        {
            name: 'Gold watch',
            category: 'Watch',
            image: '/images/watch3.jpg',
            price: 200000,
            countInStock: 3,
            brand: 'Rolex',
            rating: 5.0,
            numReviews: 15,
            description: 'Good quality watch with stylish design',
        },
        {
            name: 'Caual wear dress',
            category: 'Dress',
            image: '/images/dress4.jpg',
            price: 240000,
            countInStock: 15,
            brand: 'Prada',
            rating: 5.0,
            numReviews: 15,
            description: 'Affordable dress',
        },
        {
            name: 'Sports car Maserati',
            category: 'Car',
            image: '/images/car1.jpg',
            price: 2050000,
            countInStock: 1,
            brand: 'Maserati',
            rating: 3.5,
            numReviews: 15,
            description: 'The Maserati Super Sports Car that pushes the boundaries of time',
        },
        {
            name: 'Ferrari sports car',
            category: 'Car',
            image: '/images/car2.jpg',
            price: 2004000,
            countInStock: 2,
            brand: 'fERRARI',
            rating: 4.5,
            numReviews: 15,
            description: 'The Ferrari Super Sports Car that pushes the boundaries of time',
        },
        {
            name: 'Jeans and top',
            category: 'Dress',
            image: '/images/dress5.jpg',
            price: 215000,
            countInStock: 2,
            brand: 'Prada',
            rating: 4.0,
            numReviews: 6,
            description: 'Realy comfortable and stylish and can be used anywhere',
        },
        {
            name: 'Black watch',
            category: 'Watch',
            image: '/images/watch4.jpg',
            price: 201000,
            countInStock: 5,
            brand: 'Omega',
            rating: 4.5,
            numReviews: 15,
            description: 'Good quality watch',
        },
        {
            name: 'Lamborghini sports car',
            category: 'Car',
            image: '/images/car3.jpg',
            price: 3100000,
            countInStock: 2,
            brand: 'Lamborghini',
            rating: 5.0,
            numReviews: 20,
            description: 'Determined proportions with clear contours and precise lines and pure surfaces are characteristics of Lamborghinis design reduced to its very essence',
        },
        {
            name: 'Vacation house',
            category: 'House',
            image: '/images/p2.jpg',
            price: 1850000,
            countInStock: 8,
            brand: 'House',
            rating: 5.0,
            numReviews: 11,
            description: 'Affordable house',
        },
        {
            name: 'Mens designer',
            category: 'Suit',
            image: '/images/p5.jpg',
            price: 205000,
            countInStock: 2,
            brand: 'Gucci',
            rating: 5.0,
            numReviews: 4,
            description: 'Affordable suit',
        },
        {
            name: 'Scandinavian design',
            category: 'Chair',
            image: '/images/p6.jpg',
            price: 520000,
            countInStock: 7,
            brand: 'Wood',
            rating: 5.0,
            numReviews: 9,
            description: 'Affordable chair',
        },
        {
            name: 'Sienna minivan',
            category: 'Car',
            image: '/images/car4.jpg',
            price: 3150000,
            countInStock: 1,
            brand: 'Toyota',
            rating: 5.0,
            numReviews: 25,
            description: 'Explore the newest Sienna minivans in stock alongside other award-winning Toyota vehicles in Muscle Shoal',
        },
        {
            name: 'Toyota Camry Muscle',
            category: 'Car',
            image: '/images/car4.jpg',
            price: 2550000,
            countInStock: 4,
            brand: 'Toyota',
            rating: 4.0,
            numReviews: 30,
            description: 'The Toyota Camry Muscle comes in 5 trims - the CE, LE, XLE, SE and hybrid trims',
        },
    ],
};
export default data;